### ISSUE TITLE
root can't be './views' ?

### ISSUE THREAD

**Issue by hojas** [beliefgp/koa-nunjucks-next#5]

**Comment by beliefgp** [comment]
我们用母语吧……什么意思？  你是说root的默认值？

**Comment by hojas** [comment]
@beliefgp 也就是说，root 设置为 './views' 时不起作用，得设置为 '../views' 或者 '../../views' 这样的。相当于，初始化 koa-nunjucks-next 的文件不能和  views  在同级目录。

**Comment by beliefgp** [comment]
@hojas  
app.use(views({
    root: './views',
    extname: 'html',
    noCache: !config.templateCache,     // 缓存
    trimBlocks: config.isProduction,    // 去除 block/tag 后面的换行符
    lstripBlocks: config.isProduction,  // 去除 block/tag 签名的空格
    filters: {
        version: (url) => versionModel.getUrl(url)
    }
}));

这是我自己项目的配置，都已经上线好久了……我这边重现不了，你再确认下是不是其他问题

**Comment by hojas** [comment]
@beliefgp Sorry, 我自己的问题，犯了低级错误。
